/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ClientLayoutRouteImport } from './routes/_client-layout'
import { Route as ClientLayoutIndexRouteImport } from './routes/_client-layout/index'

const ClientLayoutRoute = ClientLayoutRouteImport.update({
  id: '/_client-layout',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLayoutIndexRoute = ClientLayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientLayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof ClientLayoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof ClientLayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_client-layout': typeof ClientLayoutRouteWithChildren
  '/_client-layout/': typeof ClientLayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/_client-layout' | '/_client-layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  ClientLayoutRoute: typeof ClientLayoutRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_client-layout': {
      id: '/_client-layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ClientLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_client-layout/': {
      id: '/_client-layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ClientLayoutIndexRouteImport
      parentRoute: typeof ClientLayoutRoute
    }
  }
}

interface ClientLayoutRouteChildren {
  ClientLayoutIndexRoute: typeof ClientLayoutIndexRoute
}

const ClientLayoutRouteChildren: ClientLayoutRouteChildren = {
  ClientLayoutIndexRoute: ClientLayoutIndexRoute,
}

const ClientLayoutRouteWithChildren = ClientLayoutRoute._addFileChildren(
  ClientLayoutRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  ClientLayoutRoute: ClientLayoutRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
